### ISSUE TITLE
401 Error not catch properly while watching

### ISSUE THREAD

**Issue by mickours** [tomplus/kubernetes_asyncio#150]
I have a code that constantly watch a deployment status but with EKS on AWS I get a 401 error after 15 min. This is an issue with EKS I'm trying to solve by reloading the configuration and I would like to have a proper exception to be able to do so. But the code is currently trying to parse a JSON field which is not there and raise:
```
Exception: Malformed JSON response, the 'object' and/or 'type' field is missing. JSON: {'kind': 'Status', 'apiVersion': 'v1', 'metadata': {}, 'status': 'Failure', 'message': 'Unauthorized', 'reason': 'Unauthorized', 'code': 401}
```

The entire stack trace is:
```
Traceback (most recent call last):
  File "/home/mmercier/Projects/ryax/runner/ryax_runner/infrastructure/k8s/k8s_engine.py", line 134, in watch_deployment
    await self._do_watch_deployment(deployment_id, message_bus)
  File "/home/mmercier/Projects/ryax/runner/ryax_runner/infrastructure/k8s/k8s_engine.py", line 100, in _do_watch_deployment
    async for event in stream:
  File "/home/mmercier/.cache/pypoetry/virtualenvs/ryax-runner-CrYYwvXC-py3.8/lib/python3.8/site-packages/kubernetes_asyncio/watch/watch.py", line 124, in __anext__
    return await self.next()
  File "/home/mmercier/.cache/pypoetry/virtualenvs/ryax-runner-CrYYwvXC-py3.8/lib/python3.8/site-packages/kubernetes_asyncio/watch/watch.py", line 163, in next
    return self.unmarshal_event(line, self.return_type)
  File "/home/mmercier/.cache/pypoetry/virtualenvs/ryax-runner-CrYYwvXC-py3.8/lib/python3.8/site-packages/kubernetes_asyncio/watch/watch.py", line 84, in unmarshal_event
    raise Exception(("Malformed JSON response, the 'object' and/or "
Exception: Malformed JSON response, the 'object' and/or 'type' field is missing. JSON: {'kind': 'Status', 'apiVersion': 'v1', 'metadata': {}, 'status': 'Failure', 'message': 'Unauthorized', 'reason': 'Unauthorized', 'code': 401}
```

**Comment by pydo** [comment]
I still encounter this error after watching a GKE cluster for about 10-15mins with the hotfix `v12.1.1`.

```
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-3' coro=<watch_pods() done, defined at /home/user/coding/k8s_events_logger/src/k8s_asyncio.py:26> exception=Exception("Malformed JSON response, the 'object' and/or 'type' field is missing. JSON: {'kind': 'Status', 'apiVersion': 'v1', 'metadata': {}, 'status': 'Failure', 'message': 'Unauthorized', 'reason': 'Unauthorized', 'code': 401}")>
Traceback (most recent call last):
  File "/home/user/coding/k8s_events_logger/src/k8s_asyncio.py", line 31, in watch_pods
    async for event in stream:
  File "/home/user/coding/k8s_events_logger/venv/lib/python3.9/site-packages/kubernetes_asyncio/watch/watch.py", line 126, in __anext__
    return await self.next()
  File "/home/user/coding/k8s_events_logger/venv/lib/python3.9/site-packages/kubernetes_asyncio/watch/watch.py", line 165, in next
    return self.unmarshal_event(line, self.return_type)
  File "/home/user/coding/k8s_events_logger/venv/lib/python3.9/site-packages/kubernetes_asyncio/watch/watch.py", line 84, in unmarshal_event
    raise Exception(("Malformed JSON response, the 'object' and/or "
Exception: Malformed JSON response, the 'object' and/or 'type' field is missing. JSON: {'kind': 'Status', 'apiVersion': 'v1', 'metadata': {}, 'status': 'Failure', 'message': 'Unauthorized', 'reason': 'Unauthorized', 'code': 401}

```

**Comment by tomplus** [comment]
@pydo confirmed... sorry. The next hot fix is on the way

**Comment by pydo** [comment]
> @pydo confirmed... sorry. The next hot fix is on the way

Thanks for the quick fix :bow:
