### ISSUE TITLE
Add example for using the exec endpoint

### ISSUE THREAD

**Issue by horazont** [tomplus/kubernetes_asyncio#174]
The synchronous version of this package has [the `pod_exec.py` example](https://github.com/kubernetes-client/python/blob/master/examples/pod_exec.py). I have tried to replicate the same with kubernetes-asyncio, but it's not clear to me how. The following does not seem to work:

```python
#!/usr/bin/env python3
import asyncio

import kubernetes_asyncio
import kubernetes_asyncio.stream as kstream
import kubernetes_asyncio.client as kclient


async def amain():
    try:
        kubernetes_asyncio.config.load_incluster_config()
    except Exception:
        await kubernetes_asyncio.config.load_kube_config()
    config = kubernetes_asyncio.client.Configuration.get_default_copy()
    async with kclient.ApiClient(config) as client:
        async with kstream.WsApiClient(config) as ws_client:
            ws_core_v1 = kclient.CoreV1Api(ws_client)
            print(await ws_core_v1.connect_post_namespaced_pod_exec(
                "busybox-test",
                "default",
                command=["/bin/true"],
                tty="false",
                stdin="false",
                stdout="false",
                stderr="false",
                _preload_content=False,
            ))


if __name__ == "__main__":
    asyncio.run(amain())

```

It fails with:

```
wss://172.30.80.33:8888/api/v1/namespaces/default/pods/busybox-test/exec?command=%2Fbin%2Ftrue&stderr=false&stdin=false&stdout=false&tty=false {'Accept': '*/*', 'User-Agent': 'OpenAPI-Generator/19.15.0/python', 'sec-websocket-protocol': 'v4.channel.k8s.io'}
Traceback (most recent call last):
  File "/home/jssfr/Work/ch/yaook/operator/exectest.py", line 31, in <module>
    asyncio.run(amain())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/jssfr/Work/ch/yaook/operator/exectest.py", line 18, in amain
    print(await ws_core_v1.connect_post_namespaced_pod_exec(
  File "/home/jssfr/Work/ch/yaook/operator/.direnv/python-3.9.9/lib/python3.9/site-packages/kubernetes_asyncio/client/api_client.py", line 182, in __call_api
    response_data = await self.request(
  File "/home/jssfr/Work/ch/yaook/operator/.direnv/python-3.9.9/lib/python3.9/site-packages/kubernetes_asyncio/stream/ws_client.py", line 93, in request
    return await self.rest_client.pool_manager.ws_connect(url, headers=headers)
  File "/home/jssfr/Work/ch/yaook/operator/.direnv/python-3.9.9/lib/python3.9/site-packages/aiohttp/client.py", line 792, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 400, message='Invalid response status', url=URL('wss://172.30.80.33:8888/api/v1/namespaces/default/pods/busybox-test/exec?command=/bin/true&stderr=false&stdin=false&stdout=false&tty=false')
```

It would be good to have a working reference example which uses the exec endpoint to run a command inside a pod.

**Comment by tomplus** [comment]
There is an example `examples/example3.py` with the exec command. Could you check if it works for you?

**Comment by horazont** [comment]
It works! I didn't find it because I was grepping the installed package, not the original source :/. My fault. I'll play with that, thanks!
