### ISSUE TITLE
Config reader does not support bool types

### ISSUE THREAD

**Issue by ChrisLovering** [tomplus/kubernetes_asyncio#217]
Using version 24.2.1, given a kube config such as the below
```yml
apiVersion: v1
kind: Config
clusters:
  - name: my_cluster
    cluster:
      insecure-skip-tls-verify: false
      server: >-
        https://valid.url.com:443
      certificate-authority-data: >-
        valid_authority_data
users:
  - name: chris
    user:
      token: >-
        a_valid_token
contexts:
  - name: my_cluster
    context:
      cluster: my_cluster
      name: my_cluster
      user: chris
      namespace: default
preferences: {}
current-context: my_cluster
```

[This line](https://github.com/tomplus/kubernetes_asyncio/blob/master/kubernetes_asyncio/config/kube_config.py#L365) will error, due to what I think is the [`safe_get`](https://github.com/tomplus/kubernetes_asyncio/blob/master/kubernetes_asyncio/config/kube_config.py#L407-L410) in the custom [`__getitem__`](https://github.com/tomplus/kubernetes_asyncio/blob/master/kubernetes_asyncio/config/kube_config.py#L412-L421) not supporting bool values, such as is the case with the `insecure-skip-tls-verify: false` line. 

I believe this is the case as changing that line to `insecure-skip-tls-verify: 'false'` makes it work for kubernetes_asyncio.

However, i think this behaviour is a bug with kubernetes_asyncio, as making this change then causes kubectl to error when parsing the key.

Full traceback of error in `kubernetes_asyncio`:
```
🕙 11:36:11 ❯ poetry run task start
Traceback (most recent call last):
  File "C:\Users\chris\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\chris\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\chris\src\king-arthur\arthur\__main__.py", line 37, in <module>
    asyncio.run(main())
  File "C:\Users\chris\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\chris\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\chris\src\king-arthur\arthur\__main__.py", line 33, in main
    await bot.start(CONFIG.token)
  File "C:\Users\chris\src\king-arthur\.venv\lib\site-packages\discord\client.py", line 745, in start
    await self.login(token)
  File "C:\Users\chris\src\king-arthur\.venv\lib\site-packages\discord\client.py", line 589, in login
    await self.setup_hook()
  File "C:\Users\chris\src\king-arthur\arthur\bot.py", line 46, in setup_hook
    await config.load_kube_config()
  File "C:\Users\chris\src\king-arthur\.venv\lib\site-packages\kubernetes_asyncio\config\kube_config.py", line 572, in load_kube_config
    await loader.load_and_set(config)
  File "C:\Users\chris\src\king-arthur\.venv\lib\site-packages\kubernetes_asyncio\config\kube_config.py", line 380, in load_and_set
    self._load_cluster_info()
  File "C:\Users\chris\src\king-arthur\.venv\lib\site-packages\kubernetes_asyncio\config\kube_config.py", line 365, in _load_cluster_info
    self.verify_ssl = not self._cluster['insecure-skip-tls-verify']
  File "C:\Users\chris\src\king-arthur\.venv\lib\site-packages\kubernetes_asyncio\config\kube_config.py", line 415, in __getitem__
    raise ConfigException(
kubernetes_asyncio.config.config_exception.ConfigException: Invalid kube-config file. Expected key insecure-skip-tls-verify in C:\Users\chris/.kube/config/{'name': 'my_cluster', 'cluster': {'insecure-skip-tls-verify': False, 'server': '{{redacted}}', 'certificate-authority-data': 'redacted'}}/cluster
```

**Comment by tomplus** [comment]
Thanks for reporting this issue. I'm working on it.
