### ISSUE TITLE
shlex.split is causing google_auth_credentials to fail on Windows

### ISSUE THREAD

**Issue by hrichardlee** [tomplus/kubernetes_asyncio#223]
This is similar to #110 

On Windows, with a GKE config as the default, if you run:

```
import asyncio
import kubernetes_asyncio.config

asyncio.run(kubernetes_asyncio.config.load_kube_config())
```

it will fail with:

```
Traceback (most recent call last):
  File "reproduce_kubernetes_asyncio_issue.py", line 4, in <module>
    asyncio.run(kubernetes_asyncio.config.load_kube_config())
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\<username>\AppData\Local\pypoetry\Cache\virtualenvs\myenv-AO7drsl8-py3.9\lib\site-packages\kubernetes_asyncio\config\kube_config.py", line 572, in load_kube_config
    await loader.load_and_set(config)
  File "C:\Users\<username>\AppData\Local\pypoetry\Cache\virtualenvs\myenv-AO7drsl8-py3.9\lib\site-packages\kubernetes_asyncio\config\kube_config.py", line 379, in load_and_set
    await self._load_authentication()
  File "C:\Users\<username>\AppData\Local\pypoetry\Cache\virtualenvs\myenv-AO7drsl8-py3.9\lib\site-packages\kubernetes_asyncio\config\kube_config.py", line 202, in _load_authentication
    await self.load_gcp_token()
  File "C:\Users\<username>\AppData\Local\pypoetry\Cache\virtualenvs\myenv-AO7drsl8-py3.9\lib\site-packages\kubernetes_asyncio\config\kube_config.py", line 238, in load_gcp_token
    credentials = await google_auth_credentials(config)
  File "C:\Users\<username>\AppData\Local\pypoetry\Cache\virtualenvs\myenv-AO7drsl8-py3.9\lib\site-packages\kubernetes_asyncio\config\google_auth.py", line 22, in google_auth_credentials
    proc = await cmd_exec
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python39\lib\asyncio\subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1661, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 394, in _make_subprocess_transport
    transp = _WindowsSubprocessTransport(self, protocol, args, shell,
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python39\lib\asyncio\base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 890, in _start
    self._proc = windows_utils.Popen(
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_utils.py", line 153, in __init__
    super().__init__(args, stdin=stdin_rfd, stdout=stdout_wfd,
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

The problem is that `provider['cmd-path']` is `C:\Users\<username>\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin\gcloud.cmd` which has a space in it, so it's being split up into two parts by `shlex.split`.

A suggested fix is available at https://github.com/tomplus/kubernetes_asyncio/compare/master...hrichardlee:kubernetes_asyncio:patch-1 I'm happy to open a pull request if this makes sense to you

**Comment by tomplus** [comment]
Yes, please open the pull request. It has to be fixed as you suggest. Thanks.

**Comment by hrichardlee** [comment]
Thanks! Opened the pull request
